### ISSUE TITLE
visualizing data after import & checking fig 4 figure

### ISSUE THREAD

**Issue by josephholler** [daptx/RP-Malcomb#3]
A better study would:
- report descriptive statistics (count (n), min, max, stddev) for variables as they're about to be used for analysis and report how many records are discarded due to missing data. e.g. a table for livelihood sensitivity data reporting all of the individual variables used, & the calculated variables;  a table for adaptive capacity reporting all the individual variables used (after discarding records with missing data), and descriptive statistics for the two raster inputs (after applying a mask).
- also one thing we talked about in preparation of the final revision was loading up the georeferenced/digitized map of fig 4 in QGIS and spatial join the household survey clusters to the traditional authorities to double-check that missing data is all digitized correctly and double-check that the other classifications truly match the published map.

**Comment by josephholler** [comment]
https://www.statmethods.net/stats/descriptives.html

**Comment by josephholler** [comment]
spatial join GPS points to traditional authorities in QGIS to verify which traditional authorities should be symbolized as "missing data" because none of the village points join to them

**Comment by daptx** [comment]
we have a game plan now; we are not fans of malcomb et al's lack of transparency
