### ISSUE TITLE
Notes on Spatial Errors with Households

### ISSUE THREAD

**Issue by daptx** [daptx/RP-Malcomb#6]
Pull in MWI_adm shapefile 
—> 256 count
Due to feature 196 containing an invalid geometry, fix geometries were used in Q 
MWGE62FL shapefile (DHS Household Survey Cluster points) were then brought in (you can either download from the website or export from code via st_write) 
Count points (MWGE62FL) in polygon (MWI_adm) tool was then used
Results yielded 222 features that included points & 34 that didn’t
Forest Reserve
Water Bodies
- 8 had no points
- 5 had points
    - ID_1 = 19, ID_2 = 162 (10 points)
    - Total = 20 points
    - 4 other bodies of water with edge effects
    - We ended up with a multipart polygon feature that included points that gave the body of water a score [resolve: clip beforehand]
- Starting point of problem: one feature that’s mostly lake, but also includes part of the land that in reality are various TAs along the lake
National Parks
- 3 had no points
- 3 had points (total = 3 points)
Reserves
- 5 had no points
- 3 had points (total = 7 points)

ANOTHER PROBLEM: points are randomized up to 5km
FIX: move clipping before any spatially joining household clusters to TAs

**Comment by daptx** [comment]
In regards to feature counts:
our georeferenced digitization of figure 4 yielded 202 TAs (38, 55, 50, 59) — the original paper had 203

**Comment by daptx** [comment]
Update: Household Clusters points included reserves in Malcomb’s analysis (they received a capacity score), but no people live there… so you can’t have vulnerable. This error is derived from the 5km randomization of household points. 

This was found when keeping the populated polygons only in the TA shape file (234 features)

**Comment by josephholler** [comment]
Good work diagnosing this error. The six conservation areas erroneously represented with data in Malcomb's publication are shown in `data\derived\public\ta_v_fig4.gpkg(layer:fig4_errors`
